# Generated by Django 4.1.7 on 2023-03-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(max_length=40),
        ),
    ]
