# Generated by Django 4.1.7 on 2023-03-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
